# Change these first
owner: bluelightcard # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Verify
    url: https://verify.blcshine.io/brand/BLC_UK/services
    method: GET
    headers:
      - "x-api-key: $VERIFY_API_KEY"
  - name: BLC UK Homepage
    url: https://bluelightcard.co.uk
  - name: BLC Australia Homepage
    url: https://bluelightcard.com.au
  - name: DDS UK Homepage
    url: https://www.defencediscountservice.co.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.blcshine.io
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.bluelightcard.co.uk/web/logos/blc-logo-landscape.png
  name: BlueLight Systems Status
  # introTitle: ""
  introMessage: BlueLight provides discounts and exclusive offers for health care workers, and armed forces members.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
